name: metadrive-ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  simulator_driving:
    name: simulator driving
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: git lfs pull
      - name: Build simulator docker image
        run: |
          docker build -f Dockerfile.openpilot_base -t openpilot-base .
      - name: Log Python version and scons location in docker
        run: |
          docker run --rm openpilot-base /bin/bash -c "python3 --version && which python3 && pip --version && which pip && pip list && which scons && scons --version || echo 'scons not found'"
      - name: Build openpilot in docker
        run: |
          docker run --shm-size 1G --privileged \
            -v $GITHUB_WORKSPACE:/tmp/openpilot \
            -w /tmp/openpilot \
            openpilot-base /bin/bash -c "scons -j$(nproc) || (echo 'SCons build failed' && which python3 && pip list && which scons && scons --version || echo 'scons not found after build failure')"
      - name: Log Python version and scons location in docker after build
        run: |
          docker run --rm openpilot-base /bin/bash -c "python3 --version && which python3 && pip --version && which pip && pip list && which scons && scons --version || echo 'scons not found'"
      - name: Run MetaDrive bridge test in docker
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: |
          docker run --shm-size 1G --privileged \
            -v $GITHUB_WORKSPACE:/tmp/openpilot \
            -w /tmp/openpilot \
            -e MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} \
            openpilot-base /bin/bash -c "source selfdrive/test/setup_xvfb.sh && source selfdrive/test/setup_vsound.sh && CI=1 pytest tools/sim/tests/test_metadrive_bridge.py || (echo 'Test failed' && which python3 && pip list && which scons && scons --version || echo 'scons not found after test failure')"
      - name: Log Python version and scons location in docker after test
        run: |
          docker run --rm openpilot-base /bin/bash -c "python3 --version && which python3 && pip --version && which pip && pip list && which scons && scons --version || echo 'scons not found'"
      - name: Upload simulator logs
        uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: metadrive_logs-${{ github.run_id }}
          path: ${{ github.workspace }}/.op_logs/simulator_logs
